### PR TITLE
WIP: closes #20: Build darwin/arm64 release

### LINKED ISSUE #20: Release for darwin-arm64
Hi ! 

I'm on darwin-arm64 and I can't find a release for this platform.

I think that I have read that new version of Go build this platform as default. Could you, please, check that and is it possible and easy for you, release a new version ?

In the meantime, I will try to launch promdoc in x64 emulation :) 

Thanks !

### PR DESCRIPTION
**Pull request by baprx**

### CODE REVIEW

**Comment by baprx** [comment]
Tested with @tpoindessous, MacOS users still need to run the command `xattr -dr com.apple.quarantine promdoc-darwin-arm64` to execute the file.

**Comment by tpoindessous** [comment]
> Tested with @tpoindessous, MacOS users still need to run the command `xattr -dr com.apple.quarantine promdoc-darwin-arm64` to execute the file.

We need to do this on MacOS because downloaded binaries are not trusted by default.

But it works :) 

I don't know how we could use brew to distribute binary ...

**Comment by jpreese** [comment]
@tpoindessous you can add a new formula at https://github.com/Homebrew/homebrew-core/tree/master/Formula to get a feel for how projects add new formulas to brew.

**Comment by jpreese** [comment]
LGTM!

**Pull request merged**
